//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func createUpload(headers:  HTTPHeaders) -> EventLoopFuture<Upload> {
      let uri = URI(string: "\(Server.main)/uploads")
      return send(.POST, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Upload.self)
      }
   }
   func createUpload(headers:  HTTPHeaders) -> EventLoopFuture<Fault> {
      let uri = URI(string: "\(Server.main)/uploads")
      return send(.POST, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Fault.self)
      }
   }
}


