//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

/** A set of rolled-up statistics and totals for an athlete */
public struct ActivityStats: Content {

    public var allRideTotals: ActivityTotal?

    public var allRunTotals: ActivityTotal?

    public var allSwimTotals: ActivityTotal?

    /** The highest climb ridden by the athlete. */
    public var biggestClimbElevationGain: Double?

    /** The longest distance ridden by the athlete. */
    public var biggestRideDistance: Double?

    public var recentRideTotals: ActivityTotal?

    public var recentRunTotals: ActivityTotal?

    public var recentSwimTotals: ActivityTotal?

    public var ytdRideTotals: ActivityTotal?

    public var ytdRunTotals: ActivityTotal?

    public var ytdSwimTotals: ActivityTotal?

    enum CodingKeys: String, CodingKey {
        case allRideTotals = "all_ride_totals"
        case allRunTotals = "all_run_totals"
        case allSwimTotals = "all_swim_totals"
        case biggestClimbElevationGain = "biggest_climb_elevation_gain"
        case biggestRideDistance = "biggest_ride_distance"
        case recentRideTotals = "recent_ride_totals"
        case recentRunTotals = "recent_run_totals"
        case recentSwimTotals = "recent_swim_totals"
        case ytdRideTotals = "ytd_ride_totals"
        case ytdRunTotals = "ytd_run_totals"
        case ytdSwimTotals = "ytd_swim_totals"
    }

}
