//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct Comment: Content {

    /** The identifier of the activity this comment is related to */
    public var activityId: Int?

    public var athlete: SummaryAthlete?

    /** The time at which this comment was created. */
    public var createdAt: DateTime?

    /** The unique identifier of this comment */
    public var id: Int?

    /** The content of the comment */
    public var text: String?

    enum CodingKeys: String, CodingKey {
        case activityId = "activity_id"
        case athlete = "athlete"
        case createdAt = "created_at"
        case id = "id"
        case text = "text"
    }

}
