//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct ExplorerResponse: Content {

    /** The set of segments matching an explorer request */
    public var segments: [ExplorerSegment]?

    enum CodingKeys: String, CodingKey {
        case segments = "segments"
    }

}
