//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

/** Encapsulates the errors that may be returned from the API. */
public struct Fault: Content {

    /** The set of specific errors associated with this fault, if any. */
    public var errors: [ErrorType]?

    /** The message of the fault. */
    public var message: String?

    enum CodingKeys: String, CodingKey {
        case errors = "errors"
        case message = "message"
    }

}
