//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct HeartRateZoneRanges: Content {

    /** Whether the athlete has set their own custom heart rate zones */
    public var customZones: Bool?

    public var zones: ZoneRanges?

    enum CodingKeys: String, CodingKey {
        case customZones = "custom_zones"
        case zones = "zones"
    }

}
