//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct Lap: Content {

    public var activity: MetaActivity?

    public var athlete: MetaAthlete?

    /** The lap's average cadence */
    public var averageCadence: Float?

    /** The lap's average speed */
    public var averageSpeed: Float?

    /** The lap's distance, in meters */
    public var distance: Float?

    /** The lap's elapsed time, in seconds */
    public var elapsedTime: Int?

    /** The end index of this effort in its activity's stream */
    public var endIndex: Int?

    /** The unique identifier of this lap */
    public var id: Int?

    /** The index of this lap in the activity it belongs to */
    public var lapIndex: Int?

    /** The maximum speed of this lat, in meters per second */
    public var maxSpeed: Float?

    /** The lap's moving time, in seconds */
    public var movingTime: Int?

    /** The name of the lap */
    public var name: String?

    /** The athlete's pace zone during this lap */
    public var paceZone: Int?

    public var split: Int?

    /** The time at which the lap was started. */
    public var startDate: DateTime?

    /** The time at which the lap was started in the local timezone. */
    public var startDateLocal: DateTime?

    /** The start index of this effort in its activity's stream */
    public var startIndex: Int?

    /** The elevation gain of this lap, in meters */
    public var totalElevationGain: Float?

    enum CodingKeys: String, CodingKey {
        case activity = "activity"
        case athlete = "athlete"
        case averageCadence = "average_cadence"
        case averageSpeed = "average_speed"
        case distance = "distance"
        case elapsedTime = "elapsed_time"
        case endIndex = "end_index"
        case id = "id"
        case lapIndex = "lap_index"
        case maxSpeed = "max_speed"
        case movingTime = "moving_time"
        case name = "name"
        case paceZone = "pace_zone"
        case split = "split"
        case startDate = "start_date"
        case startDateLocal = "start_date_local"
        case startIndex = "start_index"
        case totalElevationGain = "total_elevation_gain"
    }

}
