//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

/** A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
public typealias LatLng = [Float]
