//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct MetaClub: Content {

    /** The club's unique identifier. */
    public var id: Int?

    /** The club's name. */
    public var name: String?

    /** Resource state, indicates level of detail. Possible values: 1 -> "meta", 2 -> "summary", 3 -> "detail" */
    public var resourceState: Int?

    enum CodingKeys: String, CodingKey {
        case id = "id"
        case name = "name"
        case resourceState = "resource_state"
    }

}
