//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct MetaActivity: Content {

    /** The unique identifier of the activity */
    public var id: Int?

    enum CodingKeys: String, CodingKey {
        case id = "id"
    }

}
