//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct MetaAthlete: Content {

    /** The unique identifier of the athlete */
    public var id: Int?

    enum CodingKeys: String, CodingKey {
        case id = "id"
    }

}
