//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct PhotosSummary: Content {

    /** The number of photos */
    public var count: Int?

    public var primary: Primary?

    public struct Primary: Content {

        public var id: Int?

        public var source: Int?

        public var uniqueId: String?

        public var urls: [String: String]?

        enum CodingKeys: String, CodingKey {
            case id = "id"
            case source = "source"
            case uniqueId = "unique_id"
            case urls = "urls"
        }

    }

    enum CodingKeys: String, CodingKey {
        case count = "count"
        case primary = "primary"
    }

}
