//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct PowerZoneRanges: Content {

    public var zones: ZoneRanges?

    enum CodingKeys: String, CodingKey {
        case zones = "zones"
    }

}
