//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct StreamSet: Content {

    public var altitude: AltitudeStream?

    public var cadence: CadenceStream?

    public var distance: DistanceStream?

    public var gradeSmooth: SmoothGradeStream?

    public var heartrate: HeartrateStream?

    public var latlng: LatLngStream?

    public var moving: MovingStream?

    public var temp: TemperatureStream?

    public var time: TimeStream?

    public var velocitySmooth: SmoothVelocityStream?

    public var watts: PowerStream?

    enum CodingKeys: String, CodingKey {
        case altitude = "altitude"
        case cadence = "cadence"
        case distance = "distance"
        case gradeSmooth = "grade_smooth"
        case heartrate = "heartrate"
        case latlng = "latlng"
        case moving = "moving"
        case temp = "temp"
        case time = "time"
        case velocitySmooth = "velocity_smooth"
        case watts = "watts"
    }

}
