//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

/** Stores the exclusive ranges representing zones and the time spent in each. */
public typealias TimedZoneDistribution = [TimedZoneRange]
