//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

/** A union type representing the time spent in a given zone. */
public struct TimedZoneRange: Content {

    /** The maximum value in the range. */
    public var max: Int?

    /** The minimum value in the range. */
    public var min: Int?

    /** The number of seconds spent in this zone */
    public var time: Int?

    enum CodingKeys: String, CodingKey {
        case max = "max"
        case min = "min"
        case time = "time"
    }

}
