//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct Upload: Content {

    /** The identifier of the activity this upload resulted into */
    public var activityId: Int?

    /** The error associated with this upload */
    public var error: String?

    /** The external identifier of the upload */
    public var externalId: String?

    /** The unique identifier of the upload */
    public var id: Int?

    /** The unique identifier of the upload in string format */
    public var idStr: String?

    /** The status of this upload */
    public var status: String?

    enum CodingKeys: String, CodingKey {
        case activityId = "activity_id"
        case error = "error"
        case externalId = "external_id"
        case id = "id"
        case idStr = "id_str"
        case status = "status"
    }

}
