//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct Zones: Content {

    public var heartRate: HeartRateZoneRanges?

    public var power: PowerZoneRanges?

    enum CodingKeys: String, CodingKey {
        case heartRate = "heart_rate"
        case power = "power"
    }

}
