//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct ZoneRange: Content {

    /** The maximum value in the range. */
    public var max: Int?

    /** The minimum value in the range. */
    public var min: Int?

    enum CodingKeys: String, CodingKey {
        case max = "max"
        case min = "min"
    }

}
