//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
    private func genericRequest<T: Content>(method: HTTPMethod, url: URI, headers:  HTTPHeaders, returnType: T.Type, with client: Client) -> EventLoopFuture<T> {
        return client.send(method, headers: headers, to: url)
            .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(returnType.self)
        }
    }
}
public enum Server {
    public static let version = "3.0.0"
    public static let main = "https://www.strava.com/api/v3"
}
