//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func getRoutesByAthleteId(headers:  HTTPHeaders) -> EventLoopFuture<[Route]> {
      let uri = URI(string: "\(Server.main)/athletes/{id}/routes")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode([Route].self)
      }
   }
   func getRoutesByAthleteId(headers:  HTTPHeaders) -> EventLoopFuture<Fault> {
      let uri = URI(string: "\(Server.main)/athletes/{id}/routes")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Fault.self)
      }
   }
}


