//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func getLoggedInAthleteStarredSegments(headers:  HTTPHeaders) -> EventLoopFuture<[SummarySegment]> {
      let uri = URI(string: "\(Server.main)/segments/starred")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode([SummarySegment].self)
      }
   }
   func getLoggedInAthleteStarredSegments(headers:  HTTPHeaders) -> EventLoopFuture<Fault> {
      let uri = URI(string: "\(Server.main)/segments/starred")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Fault.self)
      }
   }
}


