//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func starSegment(headers:  HTTPHeaders) -> EventLoopFuture<DetailedSegment> {
      let uri = URI(string: "\(Server.main)/segments/{id}/starred")
      return send(.PUT, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(DetailedSegment.self)
      }
   }
   func starSegment(headers:  HTTPHeaders) -> EventLoopFuture<Fault> {
      let uri = URI(string: "\(Server.main)/segments/{id}/starred")
      return send(.PUT, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Fault.self)
      }
   }
}


