//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func getClubMembersById(headers:  HTTPHeaders) -> EventLoopFuture<[SummaryAthlete]> {
      let uri = URI(string: "\(Server.main)/clubs/{id}/members")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode([SummaryAthlete].self)
      }
   }
   func getClubMembersById(headers:  HTTPHeaders) -> EventLoopFuture<Fault> {
      let uri = URI(string: "\(Server.main)/clubs/{id}/members")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Fault.self)
      }
   }
}


