//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func getLoggedInAthleteClubs(headers:  HTTPHeaders) -> EventLoopFuture<[SummaryClub]> {
      let uri = URI(string: "\(Server.main)/athlete/clubs")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode([SummaryClub].self)
      }
   }
   func getLoggedInAthleteClubs(headers:  HTTPHeaders) -> EventLoopFuture<Fault> {
      let uri = URI(string: "\(Server.main)/athlete/clubs")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Fault.self)
      }
   }
}


