//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func getLoggedInAthleteZones(headers:  HTTPHeaders) -> EventLoopFuture<Zones> {
      let uri = URI(string: "\(Server.main)/athlete/zones")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Zones.self)
      }
   }
   func getLoggedInAthleteZones(headers:  HTTPHeaders) -> EventLoopFuture<Fault> {
      let uri = URI(string: "\(Server.main)/athlete/zones")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Fault.self)
      }
   }
}


