//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func updateLoggedInAthlete(headers:  HTTPHeaders) -> EventLoopFuture<DetailedAthlete> {
      let uri = URI(string: "\(Server.main)/athlete")
      return send(.PUT, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(DetailedAthlete.self)
      }
   }
   func updateLoggedInAthlete(headers:  HTTPHeaders) -> EventLoopFuture<Fault> {
      let uri = URI(string: "\(Server.main)/athlete")
      return send(.PUT, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Fault.self)
      }
   }
}


