//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func getCommentsByActivityId(headers:  HTTPHeaders) -> EventLoopFuture<[Comment]> {
      let uri = URI(string: "\(Server.main)/activities/{id}/comments")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode([Comment].self)
      }
   }
   func getCommentsByActivityId(headers:  HTTPHeaders) -> EventLoopFuture<Fault> {
      let uri = URI(string: "\(Server.main)/activities/{id}/comments")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Fault.self)
      }
   }
}


