//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func getLapsByActivityId(headers:  HTTPHeaders) -> EventLoopFuture<[Lap]> {
      let uri = URI(string: "\(Server.main)/activities/{id}/laps")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode([Lap].self)
      }
   }
   func getLapsByActivityId(headers:  HTTPHeaders) -> EventLoopFuture<Fault> {
      let uri = URI(string: "\(Server.main)/activities/{id}/laps")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Fault.self)
      }
   }
}


