//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func updateActivityById(headers:  HTTPHeaders) -> EventLoopFuture<DetailedActivity> {
      let uri = URI(string: "\(Server.main)/activities/{id}")
      return send(.PUT, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(DetailedActivity.self)
      }
   }
   func updateActivityById(headers:  HTTPHeaders) -> EventLoopFuture<Fault> {
      let uri = URI(string: "\(Server.main)/activities/{id}")
      return send(.PUT, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(Fault.self)
      }
   }
}


